### PR TITLE
change in dependent version of m4tthumphrey/php-gitlab-api

### PR DESCRIPTION
**Pull request by flandera**

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @flandera 

Thanks for the PR. Actually, I cannot migrate to v8 of m4tthumphrey/php-gitlab-api this easily.
You may notice in the composer.json that I'm not actually using the "real" m4tthumphrey/php-gitlab-api but a fork I made myself to add missing methods (regarding fetching Gitlab artifacts).

I'm in the process of submitting a PR to m4tthumphrey/php-gitlab-api to add this support. When the PR is done and accepted, then I can switch to v8.

**Comment by flandera** [comment]
Hello moufmouf,
actually I made this change, because when I attempted to perform install via composer, it throws an error when installing this dependecy package m4tthumprey/php-gitlab-api that this version doesn´t exist. I loooked into this repository and it seems, that last version was 7.15 an then 8. Version 7.16 which is in your composer json doesn´t exist. https://github.com/m4tthumphrey/php-gitlab-api/releases

**Comment by moufmouf** [comment]
@flandera Indeed. You cannot install the washingmachine as a require-dev dependency or a global dependency (because of this issue with php-gitlab-api). I realize the README.md is at fault here.

Instead, you can do:

```
composer create-project thecodingmachine/washingmachine washingmachine ^1.2 --stability=dev
```

This will install the washingmachine in a separate directory.

When php-gitlab-api merges thiss PR: https://github.com/m4tthumphrey/php-gitlab-api/pull/196, we will be able to use wahingmachine as a require-dev dependency or a global dependency

**Comment by flandera** [comment]
OK, thanks for the hint:-)

**Comment by moufmouf** [comment]
Fixed the documentation in the soon to be merged commit: https://github.com/thecodingmachine/washingmachine/pull/9/commits/795027ec2c39faf8d7f10e0c563fdb98b9c21bf5

**Comment by moufmouf** [comment]
Closed by #9

**Pull request closed without merging**
